### ISSUE TITLE
Class 'Model<T, R>' incorrectly implements interface 'IModel<T, R>'

### ISSUE THREAD

**Issue by Synthx** [couchbaselabs/node-ottoman#647] opened 2022-03-31 07:34 UTC
Hello,
I'm currently using Ottoman for my Couchbase server SDK,
But when I'm trying to build with `tsc`, I got the following error :

```
node_modules/ottoman/lib/types/model/model.d.ts:8:22 - error TS2420: Class 'Model<T, R>' incorrectly implements interface 'IModel<T, R>'.
  Type 'Model<T, R>' is missing the following properties from type 'IModel<T, R>': find, count, findById, findOne, and 13 more.

8 export declare class Model<T = any, R = any> extends Document implements IModel<T, R> {

```

Node version : v16.13.2
Npm version : 8.5.5
Ottoman version : 2.2.0

TSConfig file :
```
{
    "compilerOptions": {
        "module": "commonjs",
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noImplicitReturns": true,
        "noImplicitAny": false,
        "noUnusedLocals": true,
        "resolveJsonModule": true,
        "outDir": "lib",
        "sourceMap": true,
        "strict": true,
        "target": "es2017",
        "types": ["node", "puppeteer"]
    },
    "compileOnSave": true,
    "include": ["src"]
}

```

Thanks for your help

**Comment by gsi-alejandro** [comment] 2022-03-31 16:27
hi @Synthx 

In order to solve it as quick as possible check the suggestions below:
you can use:
`tsc --skipLibCheck`

or update TSConfig with:
`skipLibCheck: true`

@Synthx 
What typescript version are you using?


Greetings.

**Comment by Synthx** [comment] 2022-04-01 05:54
Hi, my typescript version is `^4.4.4`

**Comment by gsi-alejandro** [comment] 2022-04-01 14:38
Thank you @Synthx. 

I will check this typescript version. (Ottoman was built with 4.3.5)

for this reason, I suggest the 2 solutions above.

@Synthx the problem was solved by using `skipLibCheck` option?

**Comment by Synthx** [comment] 2022-04-08 16:34
Sorry, for not responded, still the same issue by downgrading my typescript version to `4.3.5`

**Comment by gsi-alejandro** [comment] 2022-04-08 18:39
Hi @Synthx 

Do you have the code in a public repor or can share a little script reproducing it, to can check and correct this.

Or any other clue to help us to reproduce this issue?

**Comment by kishmiryan-karlen** [comment] 2022-04-21 12:36
I'm having the same problem and I guess this issue is a duplicate of #604.

**Comment by gsi-alejandro** [comment] 2022-04-21 16:50
Duplicated: please check https://github.com/couchbaselabs/node-ottoman/issues/604.

**Comment by caw-ishikajain** [comment] 2022-08-27 13:41
Is this resolved? I am also unable to install ottoman
NPM 8.5.5
Node: 17.8.0

**Comment by AV25242** [comment] 2022-10-10 20:48
@gsi-alejandro  assuming this is resolved ?

**Comment by busheezy** [comment] 2022-10-14 14:14
I just ran into this as well. 

node v16.16.0
typescript" "^4.8.4"

**Comment by gsi-alejandro** [comment] 2022-10-18 14:17
Duplicated: please check https://github.com/couchbaselabs/node-ottoman/issues/604.

**Closed by gsi-alejandro** 2022-10-18 14:17 UTC
Labels: Investigation
