### ISSUE TITLE
Sometimes ensureIndexes fails

### ISSUE THREAD

**Issue by zachlankton** [couchbaselabs/node-ottoman#610] opened 2021-11-12 20:00 UTC
## UPDATE (TL;DR)
For those searching this issue and looking for a quick fix: a forked and patched version of ottoman is available at [https://github.com/zachlankton/node-ottoman/tree/610-ensure-fix](https://github.com/zachlankton/node-ottoman/tree/610-ensure-fix).  
This will only be maintained until the patch is published in the official repo. ( Currently pending PR: #611 )

It can also be installed with NPM:
```
npm install ottoman@npm:@zachwritescode/ottoman
```
Alternatively, you can update your package.json dependencies with:
```
"ottoman": "npm:@zachwritescode/ottoman@^2.0.1",
```

## Original Post:
Hello, I am experiencing an intermittent error.

```powershell
Ensuring Indexes...
[Error: LCB_ERR_KEYSPACE_NOT_FOUND (404): Keyspace is not found (collection or bucket does not exist)] {
  code: 404,
  ctxtype: 'query',
  first_error_code: 12003,
  first_error_message: 'Keyspace not found in CB datastore: default:connext._default.UserProfile',
  statement: 'BUILD INDEX ON `connext`.`_default`.`UserProfile`(`Ottoman_defaultUserProfile`) USING GSI',
  client_context_id: 'd9c1ccc274582b8e',
  parameters: '',
  http_response_code: 500,
  http_response_body: ''
}
```

This only happens sometimes when calling the `await start()` stand alone function.  However, this error never occurs when I do the following:

```typescript

await ottoman.connect(cnx)
await ottoman.ensureCollections()
await pause(1000); //Helper function to force delays
await ottoman.ensureIndexes();

```

I've written a test script that reproduces the problem pretty reliably ( strange for an intermittent problem 😊 ) 
It also runs a separate set of tests using the above solution as well as using the couchbase node.js SDK directly with no pause and also with a pause between creating the collection and creating the index.  

It appears the main issue is needing a delay between creating collection and creating indexes, regardless if done through ottoman or couchbase node sdk?

You can get the test script here [https://gist.github.com/zachlankton/aaaa7d6d1cc1ee34e0974bc1ee05b191](https://gist.github.com/zachlankton/aaaa7d6d1cc1ee34e0974bc1ee05b191)

Here is a snapshot of the results I'm getting from this script on my machine:

```powershell
PS C:\Users\zachl\Documents\ottoman-test> node ottoman-test.mjs

Testing Ottoman with Start....
Had 5 errors out of 10 tests 

Testing Ottoman with Pause....
Had 0 errors out of 10 tests 

Testing with Couchbase....
Had 7 errors out of 10 tests 

Testing with Couchbase Pause...
Had 0 errors out of 10 tests 
```

**Comment by zachlankton** [comment] 2021-11-12 20:11
I am also using the latest couchbase docker image with these tests on my Windows Machine:

```powershell
[System Summary]

Item	Value	
OS Name	Microsoft Windows 10 Home	
Version	10.0.19042 Build 19042	
System Manufacturer	Eluktronics Inc.	
System Model	MAX-15	
System Type	x64-based PC	
System SKU	MAX-15 G1	
Processor	Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz, 2304 Mhz, 8 Core(s), 16 Logical Processor(s)
Installed Physical Memory (RAM)	64.0 GB		
```

**Comment by AV25242** [comment] 2021-11-13 16:39
Hello @zachlankton  thanks for reaching out. 
Creation of collections and indexes takes time and how long depends on your use-case, the general recommendation is for you to create these entities offline but we do realize that you would need test coverage just like in this case so what you are seeing is an intended behavior.

 Now having said that we [introduced a configuration](https://github.com/couchbaselabs/node-ottoman/blob/27714809e9bb7c15d6b92142137d9ae9f7000611/src/ottoman/ottoman.ts#L439) called `retryCount`. By default the count is 3 you can scale it to suit your needs and see if that helps solve the problem. Basically it encapsulates the delay that you manually introduced in your code.

Coming to the Indexes, its a similar behavior, just that you are not seeing it because you are not using Indexes immediately, had you been running a query that uses the Indexes you would have noticed a failure if the Indexes are not created.

To overcome Indexes concerns you can turnoff creation of Indexes by passing in

**Comment by zachlankton** [comment] 2021-11-13 19:06
Hello @AV25242 Thanks for the response!

I completely understand that for production we would have the db and indexes already setup and we would not use start() or `ensureCollections()` or `ensureIndexes()`.  

But for testing purposes and development this is exactly what I want!  The documentation leads me to believe that calling start() will guarantee that my collections and my indexes will be ready so that I can run queries on them without errors.  Here it seems the index creation is failing because the collection does not exist (or is not ready) yet?

If this is truly intended behavior then the documentation is not very clear here.  As it stands right now `ensureCollections()` works about 50% of the time for me.  The only sure fire way to make sure my collection is ready before running `ensureIndexes()` is to force a delay.

I notice the `ensureIndexes()` does not have the same retry logic as `ensureCollections()` that you mentioned... is this possibly what needs to be implemented in `ensureIndexes()`? 

If this seems reasonable, I can work on a fix to contribute this solution.
Let me know what you think.

**Comment by AV25242** [comment] 2021-11-13 23:00
hello @zachlankton I agree with you that there is a lot of scope to improve the documentation in this regard. 
Yes the index creation is failing because the collection didn't exist in your example (it was in the process of being created).
`ensureIndexes()` helps build indexes which is more time consuming than creation of scopes and collections and that would be one of the reasons why we dont provide you with the option of retry but instead we provide you a callback with the help of hooks like mentioned before, the hook will let you know when the Index creation is completed.

With respect to contribution, we would love to see contributions from you in any space i.e documentation or code PR. 

Also if may I take the liberty to ask, what is that you are building using Ottoman, curious to learn your usecase.

**Comment by zachlankton** [comment] 2021-11-14 05:45
Thanks @AV25242 ... I believe there was some misunderstanding here.  The error `LCB_ERR_KEYSPACE_NOT_FOUND` was not handled in way that would provide for what you describe.  The error persisted even with the `ignoreWatchIndexes` set to true and hooking into the callback. This is because the collection was not ready, so the index could not be built.

I cloned the repo and ran the test suite on the couchbase/server-sandbox database image and all tests pass wonderfully!

However, most users will not be starting with a prebuilt test database, so I ran the test suite against a fresh empty couchbase docker image and it resulted in 45 failing tests.  

6 of which were for the collection not being ready, 35 were for the index not being ready: `Planning Failures`  The last few were failures related to specific indexes provided by couchbase/server-sandbox test database image.

I modified the `tryCreateCollection` logic to guarantee the collection is ready and fixed the first 6 failing tests.

I reviewed the code and found that the "if" block for `ignoreWatchIndexes` will **_NEVER_** run because the `indexOnlinePromise` would only get set **_IF_** there were `indexReadyHooks` registered.  I refactored the logic so that `ensureIndexes` will return the `indexOnlinePromise` as it should.

Now it works the way the documentation says it does and all tests are still passing!  I will have a pull request prepared shortly.

**Comment by zachlankton** [comment] 2021-11-14 06:18
@AV25242 To answer your other question... I am actually just learning about couchbase and ottoman currently.  I have used it in some small projects for the company that I work for, nothing heavy, but I really love the developer experience that I have had so far with couchbase and ottoman, its awesome!!

The way I stumbled on this issue was when trying to build a database connecter for [next-auth](https://next-auth.js.org/) using ottoman.  So I was trying to leverage the `start()` command to ensure the collections and indexes were ready before running my queries.... That's when I started noticing that sometimes the queries would fail in my testing... and one project begets another... here I am! 😂

**Comment by ejscribner** [comment] 2022-02-08 02:31
Hey @zachlankton! Wanted to update you that this has been added in the latest release of Ottoman (v2.1.0), available now on NPM. Thanks for the support!

**Comment by zachlankton** [comment] 2022-02-08 12:29
Awesome! Thank you!

**Comment by AV25242** [comment] 2022-10-10 20:50
Closing this issue, hoping its resolved @zachlankton  if not please open a follow-up ticket

**Closed** 2022-10-10 20:50 UTC
