### ISSUE TITLE
validate() is only called pre-save

### ISSUE THREAD

**Issue by moxious** [couchbaselabs/node-ottoman#108] opened 2016-07-27 23:54 UTC
The schema validate function only gets called when you attempt to save a model.  This results in some strange/counter-intuitive behavior with validator functions.  For example:

This is an error:

```
var model = ottoman.model('Model', { a: 'string' });
model({ notALegalField: 'hello!' });
```

(Error: Could not find schema field for 'notALegalField'.)

This however, is not an error:

```
var huh = ottoman.model('Huh', { 
   a: {
     type: 'string',
     validator: function(v) { throw new Error('I fail every time!'); }
  }
});

var iShouldNotBe = new huh({a : 'hello!' });
```

If you attempted to `iShouldNotBe.save()` then it _would_ fail.

The reason this works (strangely) is because the `validate` function in schema only gets called when you try to save.  While model schema checks are applied at constructor time, validation functions are not.

Shouldn't validators also be called at construct time?

**Comment by brett19** [comment] 2016-07-27 23:59
Hey @moxious,
The issue comes from the fact that we cannot invoke validators on a per-field-changed basis.  So the safest option was to perform validation at save time.  I don't immediately see any issues with performing validation once at post-construction time, though that might break some logic I've seen with regard to validators (some people do modifications to the documents through the validators, encrypting a password for instance 👎 ) as in this case they will be invoked multiple times.
Cheers, Brett

**Comment by moxious** [comment] 2016-07-28 00:02
Whoa....modifying field values seems to me like real abuse of validators.   Granted it only recently went in, but this PR: https://github.com/couchbaselabs/node-ottoman/pull/88  was expressly intended to help out in that situation.

I get that you can't run validators whenever any old field changes, but surely if the model definition explicitly says for example that this field should be a string and it can't be empty or null, then constructing an object with an empty/null value is not OK?

Validators are hopefully cheap to run, so it wouldn't seem like there's necessarily a bad outcome to running them more than once, right?   Although if people abuse validators to do other things, I could see that causing a mess.

**Comment by brett19** [comment] 2016-07-28 17:13
Hey @moxious,
The problem is that I think people are already abusing them.  Perhaps I should just find some way to make it more difficult to abuse them and merge it with this change :).
Cheers, Brett

**Comment by moxious** [comment] 2016-07-28 17:19
This reminds me of an old quote about the perl language:

> “Perl doesn't have an infatuation with enforced privacy. It would prefer that you stayed out of its living room because you weren't invited, not because it has a shotgun”  ― Larry Wall

I don't think you should spend any time making it more difficult to abuse.  JS being a dynamic language, it's ultimately a losing proposition anyway, anybody can abuse any internals they choose.

That being said, IMHO you don't have to feel bad at all about breaking people's code when they were abusing the API to begin with. So personally I think it makes sense to call validators when you're checking data against the schema.  If that creates undesirable side effects in code that wasn't written to the API spec to begin with, then you try to compromise by maybe updating a minor version, and documenting that you did this, giving them a big red flag that if they did this, they should watch out and/or not upgrade.  But that's about the best you can do, right?   Maintaining the API to support buggy/API abuse behavior is a recipe for the API being in a straightjacket.  :)

**Comment by brett19** [comment] 2016-07-28 17:23
Hey @moxious,
Its less about trying to maintain buggy/broken API behaviour, and more to do with the fact that the more difficult you make it to abuse things, the less likely people are to accidentally end up in a bad situation in the first place.  Essentially, placing those barriers is a form of implicitly documenting that that is bad behaviour.
Cheers, Brett

**Comment by gsi-chao** [comment] 2020-11-20 17:28
Running the validations when the pre-save / post-save is run is standard behavior in most ORM / ODMs.
Eg: https://mongoosejs.com/docs/validation.html

However, in ottoman v2 the user can call the validations manually from the document.

```
const schema = new Schema({ name: String, age: { type: Number, min: 0 } });
const Person = ottoman.model('Person', schema);

let p = new Person({ name: 'foo', age: 'bar' });
// Cast to Number failed for value "bar" at path "age"
await p.validate();
```

See in details at https://v2.ottomanjs.com/guides/document.html#validating

I hope it helps

**Closed by gsi-chao** 2020-11-20 17:28 UTC
Labels: bug
