### ISSUE TITLE
updateById, updateMany, findOneAndUpdate does't support skipping validation and hooks

### ISSUE THREAD

**Issue by noiissyboy** [couchbaselabs/node-ottoman#673] opened 2022-08-24 08:44 UTC
Iam trying to update  a property/ field of a document in couchbase using ottomanjs, while using updateById, updatemany, findOneAndUpdate getting a validation or hook error response , since iam trying to update only one field/property but ottoman expects all propeties of the document  while validation and hooks execution and returns obivous error response.

is there a way  to update  a document in couchbase using ottomanjs  only sending that paticular field/ property  and  skipping  hooks and validations which was used implemented for document creation save().

The save() function triggers validate() hooks, because Ottoman has a built-in pre('save') hook that calls validate(). This means that all pre('validate') and post('validate') hooks get called before any pre('save') hooks. The updateById() function have the same behavior.

**Comment by AV25242** [comment] 2022-08-25 16:51
Thanks for adding this here.

@gsi-alejandro can you assist ?>

**Comment by gsi-alejandro** [comment] 2022-08-29 23:25
hi @noiissyboy 

can you provide a use case to reproduce this issue?

Note: This issue shouldn't happen, due to we recreate the entire object in memory before trying to update it, therefore all the fields will be present merging the existing one in the database + the ones you are trying to update.

I create this simple script to show how it works while updating partial document using updateById

```
import { Ottoman, Schema } from "ottoman";

const main = async () => {
  const ottoman = new Ottoman();
  await ottoman.connect({
    connectionString: "couchbase://192.168.0.107",
    bucketName: "travel-sample",
    username: "Administrator",
    password: "password",
  });
  
  const userSchema = new Schema({
    name: { type: String, required: true },
    email: { type: String, required: false },
  });

  const User = ottoman.model("User", userSchema);

  await ottoman.start();

  const user = new User({ name: "Test", email: "test@fake.com" });
  await user.save();

  console.log(user);

  const userUpdated = await User.updateById(user.id, { name: "Test Updated" });

  console.log(userUpdated);
};

main();

```

**Comment by noiissyboy** [comment] 2022-08-30 14:11
hi @gsi-alejandro 

I have created a nestjs project to replicate this issue, kindly check the link below
https://github.com/noiissyboy/test-ottoman

**Comment by gsi-alejandro** [comment] 2022-08-30 18:58
Hi @noiissyboy,

Is this the error message you are facing?
![image](https://user-images.githubusercontent.com/15661442/187519405-5a42aa1d-c2c8-4dc4-a594-1a33af098904.png)

Maybe you need to update the logic in the hook or change it from 'validate' to 'save':
1. Create logic to validate unique emails on pre `save` (length > 0) and `update` (length > 1 (itself)) hooks
2. Just validate when saving, only need to change pre `validate` to `save`.

**Comment by noiissyboy** [comment] 2022-08-31 13:36
Hi @gsi-alejandro  @AV25242 
Thanks for you help changing from 'validate' to 'save' helps skipping 'validate' hooks  but I am getting ValidationError for password field.
  
![exception](https://user-images.githubusercontent.com/28845290/187690887-01c169e0-8b47-4970-860e-5273bfe1ef6f.png)

Iam not sure if hook error will appear after validation as save comes after validation.

Thanks
Vignesh

**Comment by gsi-alejandro** [comment] 2022-08-31 19:38
hi @noiissyboy 

For this case you should create a validation function to use in the `save` hook, due to the string you're validating will only exist while creating; the stored value is a hash value from it. Therefore it can be registered as a validator because it should be triggered for the original value before saving it.

From this point you can create a function:
```
const passwordValidator = (value: string) => {
  const regex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{6,60}$/
  if (value && !value.match(regex)) {
    throw new BadRequestException('password doesn\'t satisfies requirement!');
  }
  return true;
}
```

And use it in the `save` hook like this:

```
preHooks: {
      'save': async (doc:any) => {
        const UserModel = getModel('User');
       
        const user= await UserModel.findOneByEmail(doc.email)
       
        if(user.rows.length >0){
          throw new ConflictException(doc.email + 'user already exist!');
        }
        if (passwordValidator(doc.password)) {
          const temp = await hash(doc.password, 12);
          doc.password = temp;
        }
      }
    }
```

or just:
```
preHooks: {
      'save': async (doc:any) => {
        const UserModel = getModel('User');
       
        const user= await UserModel.findOneByEmail(doc.email)
       
        if(user.rows.length >0){
          throw new ConflictException(doc.email + 'user already exist!');
        }

       passwordValidator(doc.password);
       const temp = await hash(doc.password, 12);
       doc.password = temp;
    }
```

**Comment by noiissyboy** [comment] 2022-09-01 07:37
Hi @gsi-alejandro ,

Thanks  that worked, kindly consider disabling validation checks for all fields while updating partial fields in ottoman by default.  since  Schema validator and validate hooks  are unused and update document is major action done in database.

**Comment by AV25242** [comment] 2022-10-10 20:04
I am closing this issue as no action is needed particularly for this issue

**Closed by AV25242** 2022-10-10 20:04 UTC
